# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('location-service-example', ['location-service'])
    obj.source = 'location-service-example.cc'

